openapi: 3.0.3
info:
  title: GPA Calculator API
  description: |
    The GPA Calculator currently uses a client-side implementation with LocalStorage.
    No server-side API is implemented. This specification is a placeholder for potential future API development.
  version: 1.0.0
servers: []
paths: {}
components: {}